// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceNsoDevice(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNsoDeviceConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.nso_device.test", "address", "10.1.1.1"),
					resource.TestCheckResourceAttr("data.nso_device.test", "port", "22"),
					resource.TestCheckResourceAttr("data.nso_device.test", "authgroup", "default"),
					resource.TestCheckResourceAttr("data.nso_device.test", "admin_state", "locked"),
					resource.TestCheckResourceAttr("data.nso_device.test", "cli_ned_id", "cisco-ios-cli-3.8:cisco-ios-cli-3.8"),
				),
			},
		},
	})
}

const testAccDataSourceNsoDeviceConfig = `

resource "nso_device" "test" {
	name = "test-device01"
	address = "10.1.1.1"
	port = 22
	authgroup = "default"
	admin_state = "locked"
	cli_ned_id = "cisco-ios-cli-3.8:cisco-ios-cli-3.8"
}

data "nso_device" "test" {
	name = "test-device01"
	depends_on = [nso_device.test]
}
`
