
// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceNsoDeviceGroup(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceNsoDeviceGroupConfig,
				Check: resource.ComposeTestCheckFunc(
				),
			},
		},
	})
}

const testAccDataSourceNsoDeviceGroupConfig = `

resource "nso_device_group" "test" {
  name = "test-group1"
  device_names = ["c1"]
}

data "nso_device_group" "test" {
  name = "test-group1"
  depends_on = [nso_device_group.test]
}
`
