// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-restconf"
)

type dataSourceDeviceType struct{}

func (t dataSourceDeviceType) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Device configuration.",

		Attributes: map[string]tfsdk.Attribute{
			"instance": {
				MarkdownDescription: "An instance name from the provider configuration.",
				Type:                types.StringType,
				Optional:            true,
			},
			"id": {
				MarkdownDescription: "The RESTCONF path.",
				Type:                types.StringType,
				Computed:            true,
			},
			"name": {
				MarkdownDescription: "A string uniquely identifying the managed device.",
				Type:                types.StringType,
				Required:            true,
			},
			"address": {
				MarkdownDescription: "IP address or host name for the management interface on the device.",
				Type:                types.StringType,
				Computed:            true,
			},
			"port": {
				MarkdownDescription: "Port for the management interface on the device. If this leaf is not configured, NCS will use a default value based on the type of device. For example, a NETCONF device uses port 830, a CLI device over SSH uses port 22, and an SNMP device uses port 161.",
				Type:                types.Int64Type,
				Computed:            true,
			},
			"authgroup": {
				MarkdownDescription: "The authentication credentials used when connecting to this managed device.",
				Type:                types.StringType,
				Computed:            true,
			},
			"admin_state": {
				MarkdownDescription: "Administrative state.",
				Type:                types.StringType,
				Computed:            true,
			},
			"netconf_net_id": {
				MarkdownDescription: "NETCONF NED ID.",
				Type:                types.StringType,
				Computed:            true,
			},
			"cli_ned_id": {
				MarkdownDescription: "CLI NED ID.",
				Type:                types.StringType,
				Computed:            true,
			},
		},
	}, nil
}

func (t dataSourceDeviceType) NewDataSource(ctx context.Context, in tfsdk.Provider) (tfsdk.DataSource, diag.Diagnostics) {
	provider, diags := convertProviderType(in)

	return dataSourceDevice{
		provider: provider,
	}, diags
}

type dataSourceDevice struct {
	provider provider
}

func (d dataSourceDevice) Read(ctx context.Context, req tfsdk.ReadDataSourceRequest, resp *tfsdk.ReadDataSourceResponse) {
	var config Device

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	res, err := d.provider.clients[config.Instance.Value].GetData(config.getPath(), restconf.Query("content", "config"))
	if res.StatusCode == 404 {
		config = Device{Instance: config.Instance}
	} else {
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
			return
		}

		config.fromBody(ctx, res.Res)
	}

	config.Id = types.String{Value: config.getPath()}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
