// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccNsoDeviceGroup(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccNsoDeviceGroupConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("nso_device_group.test", "name", "test-group1"),
					resource.TestCheckResourceAttr("nso_device_group.test", "device_names.0", "c1"),
				),
			},
			{
				ResourceName:  "nso_device_group.test",
				ImportState:   true,
				ImportStateId: "tailf-ncs:devices/device-group=test-group1",
			},
		},
	})
}

func testAccNsoDeviceGroupConfig_minimum() string {
	return `
	resource "nso_device_group" "test" {
		name = "test-group1"
	}
	`
}

func testAccNsoDeviceGroupConfig_all() string {
	return `
	resource "nso_device_group" "test" {
		name = "test-group1"
		device_names = ["c1"]
	}
	`
}
